build:
  image: 'arob/drone-nonstop-browser'
  commands:
    - 'ns --verbose'
cache:
  mount:
    - node_modules
    - .git
deploy:
  nonstop:
    image: 'jgreat/drone-nonstop'
    index: $$NONSTOP_INDEX_IP
    url: '/index/api'
    port: '4444'
    token: $$NONSTOP_TOKEN
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK
    username: 'azurebuild'
    channel: '#hackbot'
