platforms:
  darwin:
    architecture:
      - 'x64'
  linux:
    architecture:
      - 'x64'
projects:
  'nonstop-index-ui':
    path: './'
    steps:
      npm:
        path: './'
        command: 'npm'
        arguments:
          - 'install'
      pretest:
        path: './'
        command: 'gulp'
        arguments:
          - 'index:dev'
      test:
        path: './'
        command: 'npm'
        arguments:
          - 'test'
    pack:
      pattern: '*,client/**/*,public/**/*,server/**/*,tasks/**/*,node_modules/**/*'
